<?php

namespace App\Services;

use App\Models\ActivityLog;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

/**
 * Central write path for ActivityLog. Auto-captures actor/request context so
 * callers only need to supply what's specific to the action being logged.
 */
class AuditLogger
{
    public static function log(array $data): ActivityLog
    {
        if (empty($data['action'])) {
            throw new \InvalidArgumentException('AuditLogger::log() requires an "action".');
        }

        $user = $data['actor'] ?? Auth::user();
        $entity = $data['entity'] ?? null;

        $identifier = $data['entity_identifier']
            ?? (($entity && method_exists($entity, 'activityLogIdentifier')) ? $entity->activityLogIdentifier() : null);

        return ActivityLog::create([
            'user_id'             => $data['actor_id'] ?? $user?->id,
            'user_name'           => $data['actor_name'] ?? $user?->name ?? 'System',
            'actor_type'          => $data['actor_type'] ?? ($user ? 'user' : 'system'),
            'actor_role_snapshot' => $data['actor_role_snapshot'] ?? $user?->role?->value,
            'action'              => $data['action'],
            'module'              => $data['module'] ?? null,
            'entity_type'         => $data['entity_type'] ?? ($entity ? class_basename($entity) : null),
            'entity_id'           => $data['entity_id'] ?? $entity?->getKey(),
            'entity_identifier'   => $identifier,
            'old_values'          => $data['old_values'] ?? null,
            'new_values'          => $data['new_values'] ?? null,
            'details'             => $data['details'] ?? null,
            'status'              => $data['status'] ?? 'success',
            'severity'            => $data['severity'] ?? 'info',
            'session_id'          => $data['session_id'] ?? (request()->hasSession() ? request()->session()->getId() : null),
            'device_fingerprint'  => $data['device_fingerprint'] ?? self::fingerprint(),
            'trace_id'            => $data['trace_id'] ?? null,
            'ip_address'          => $data['ip_address'] ?? request()->ip(),
            'user_agent'          => $data['user_agent'] ?? request()->userAgent(),
        ]);
    }

    /**
     * A new trace_id for grouping several log entries generated by one parent
     * action (e.g. a transfer that touches two locations in one request).
     */
    public static function newTraceId(): string
    {
        return (string) Str::uuid();
    }

    /**
     * There's no client-side fingerprinting in this app (no JS collection, no
     * consent flow for it) — this is a server-derived stand-in: a stable hash
     * of IP + user agent. It distinguishes concurrent sessions from different
     * networks/browsers but is NOT a persistent per-device identifier.
     */
    protected static function fingerprint(): ?string
    {
        $seed = request()->ip() . '|' . request()->userAgent();

        return trim($seed, '|') !== '' ? substr(hash('sha256', $seed), 0, 32) : null;
    }
}
